name = "seraf-homepage"
compatibility_date = "2024-01-01"

[env.production]
name = "seraf-homepage-production"

[env.staging]
name = "seraf-homepage-staging"

# 環境変数の設定
[vars]
# EmailJS設定（実際の値に置き換えてください）
EMAILJS_PUBLIC_KEY = "s7JAyEhqGZ44jV-9E"
EMAILJS_SERVICE_ID = "service_Seraf0"
EMAILJS_TEMPLATE_ID = "template_AutoReply"
