name = "seraf-homepage"
compatibility_date = "2024-11-23"

[env.production]
name = "seraf-homepage-production"

[env.staging]
name = "seraf-homepage-staging"
 
[vars]
EMAILJS_PUBLIC_KEY = "s7JAyEhqGZ44jV-9E"
EMAILJS_SERVICE_ID = "service_Seraf0"
EMAILJS_TEMPLATE_ID = "template_AutoReply"
